# Random

In [1]:
import numpy as np

rand

In [3]:
np.random.rand(3)

array([0.53328208, 0.41247636, 0.27370548])

In [6]:
np.random.rand(5,5)

array([[0.86428938, 0.23644562, 0.0715075 , 0.77642057, 0.6362174 ],
       [0.70459669, 0.32098391, 0.8400363 , 0.6079725 , 0.37334999],
       [0.3785027 , 0.18986941, 0.13712138, 0.72295695, 0.39255767],
       [0.99771543, 0.18010622, 0.66165896, 0.53873033, 0.03685046],
       [0.85629303, 0.73854227, 0.03985805, 0.15342359, 0.24566291]])

randn

In [9]:
np.random.randn(5)

array([ 0.4340135 ,  0.16269533, -0.69468273, -0.85147287, -0.8451231 ])

In [11]:
np.random.randn(5,5)

array([[-1.77803314, -0.01397348,  0.52506928, -0.36254042,  0.4153559 ],
       [ 1.22450351, -0.35800422,  0.66363297, -0.42681891,  0.42925603],
       [-0.43885128, -1.81422162, -1.30485581,  2.63538373, -0.43206778],
       [-0.34629628,  0.0740655 ,  0.35946946,  1.66426269, -0.24947315],
       [ 1.27820595, -0.10627012, -0.70995604, -1.54144319, -0.79716642]])

randint

In [12]:
np.random.randint(1,100)

58

In [14]:
np.random.randint(1,10,10)

array([3, 2, 7, 3, 9, 3, 3, 9, 1, 3])

In [18]:
np.random.randint(-1,10+10)

15

In [19]:
np.random.randint(-1,10+10,5)

array([-1, 14, 14, 11,  9])