# Arithmetic

In [2]:
import numpy as np
arr = np.arange(0,10)

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr / arr

C:\Users\dell\AppData\Local\Temp\ipykernel_13080\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\dell\AppData\Local\Temp\ipykernel_13080\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)